// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoSomething(arg1) {
  return window['go']['main']['App']['DoSomething'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
